pub mod assistant_panel;
pub mod atlas;
pub mod background;
pub mod command_palette;
pub mod effects;
pub mod gpu;
pub mod perf;
pub mod quad;
pub mod render_state;
pub mod sphere;
pub mod text;
pub mod ui;

pub use assistant_panel::{AssistantPanel, ChatMessage, ChatRole};
pub use command_palette::CommandPalette;
pub use gpu::GpuContext;
pub use perf::FrameTimer;
pub use quad::{QuadInstance, QuadRenderer};
pub use render_state::RenderState;
pub use text::TextRenderer;
pub use ui::{PaneBorder, StatusBar, Tab, TabBar, UiChrome};
